/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Drillimpact (https://sketchfab.com/Drillimpact)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/psx-first-person-arms-efd731f559a14ab48e29c8a200d71788
Title: PSX First Person Arms
*/

import { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Bone, Group, MeshStandardMaterial, SkinnedMesh } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    Object_58: SkinnedMesh
    _rootJoint: Bone
  }
  materials: {
    arms: MeshStandardMaterial
  }
}

// type ActionName =
//   | 'arms_armature|Combat_punch_right'
//   | 'arms_armature|Collect_something'
//   | 'arms_armature|Combat_idle_loop'
//   | 'arms_armature|Combat_idle_start'
//   | 'arms_armature|Combat_punch_left'
//   | 'arms_armature|Hands_below'
//   | 'arms_armature|Magic_spell_attack'
//   | 'arms_armature|Magic_spell_loop'
//   | 'arms_armature|Magic_spell_loop_start'
//   | 'arms_armature|Relax_hands_idle_loop'
//   | 'arms_armature|Relax_hands_idle_start'

export function Arms(props: JSX.IntrinsicElements['group']) {
  const group = useRef<Group>(null)
  const { nodes, materials, animations } = useGLTF(
    '/psx_first_person_arms.glb'
  ) as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const idleAction = actions['arms_armature|Relax_hands_idle_loop']
    if (idleAction) {
      idleAction.play()
    } else {
      console.error('idle animation error')
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Sketchfab_Scene"
        rotation={[0, Math.PI, 0]}
        scale={[0.23, 0.23, 0.23]}
        position={[0, -1.22, -0.1]}
      >
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.95}
        >
          <group
            name="PSX_First_Person_Armsfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="arms_armature"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_58"
                      geometry={nodes.Object_58.geometry}
                      material={materials.arms}
                      skeleton={nodes.Object_58.skeleton}
                    />
                    <group name="Object_57" />
                  </group>
                </group>
                <group name="arms" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/psx_first_person_arms.glb')
